### ISSUE TITLE
Add binaries to releases page

### ISSUE THREAD

**Issue by Keith94** [Orbmu2k/nvidiaProfileInspector#14]
Will you please add new versions of the program to the [releases page](https://github.com/Orbmu2k/nvidiaProfileInspector/releases)? It would be a little more streamlined for people to discover it, mainly because there's no link to the appveyor.com page here.

**Comment by frame** [comment]
In case anyone else is looking for the link: https://ci.appveyor.com/project/Orbmu2k/nvidiaprofileinspector/build/artifacts (appveyor.com) contains the current build.

**Comment by meffect** [comment]
this is the most amateur level shit i ever seen for a application that ALMOST EVERYONE IN THE FUCKING WORLD USES. IM GONNA DOWNLOAD EXE FROM SOME RANDOM FUCKIN WEBSITE BRO

**Comment by DarkStarSword** [comment]
It is unusual, but speaking as devil's advocate it is not entirely amateur - this is coming from the Continuous Integration line of thinking, and one advantage that I can see is that website lists the exact git SHA that it was built from, so you can actually be sure the code you are running matches the source you see here on github, which is not actually the case for other projects where we have to trust that whoever built the code did so from the source they claim to have and did not insert anything malicious, whether intentionally or not (like, if their build system was infected with a virus this might happen without their knowledge. There has been some moves in the last couple of years to try to solve this source-binary verification problem, but that turns out to be really hard).

The biggest problem I see with encouraging using this CI website to download the project is that it will build anything pushed to this github page immediately and publish it as the latest build - but, that includes pull requests that anyone could send in, which may include changes the developer would rather reject, amateur bugs or worse. The potential for abuse is limited only by the fact that we can see the source code of whatever is pushed so we can see if someone is tries something dodgy and act quickly to rectify the situation - but, if that were to happen, we may not be able to act quickly enough and for this reason I would encourage the developer to switch to using the releases page as well.

**Comment by meffect** [comment]
im gonna need some time to read big length

**Comment by DeadManWalkingTO** [comment]
[DeadManWalkingTO/NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW)
forked from [Orbmu2k/nvidiaProfileInspector](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW)

Release Binaries (New Versions - Updates)

**Comment by Orbmu2k** [comment]
i have disabled CI builds for pullrequest, to get avoid of this problem @DarkStarSword mentioned above.

i may also look into automated release builds via appveyor later
