### ISSUE TITLE
Higher or custom frame rate limiter. Please

### ISSUE THREAD

**Issue by ghost** [Orbmu2k/nvidiaProfileInspector#19]
I wan't to limit my fps to exactly 300 but in the latest version the highest possible number is 255, and in the old version the highest was 290.

I know the feature to set custom values with CustomSettingNames_en-EN.xml is removed in the latest update of Nvidia inspector/Nvidia profile inspector. But even tho in the older versions when I can still set a custom value of Fps I get a warning saying "unhandled exception uint 32" and I can't set a custom frame rate value.

Could it be possible for you to bring back a way to edit the values (without getting "unhandled exception uint 32").
Or releasing a new update with instead of 255 fps as the maximum, it is 300.

I would be really happy if you could do this. Thank You!

**Comment by Orbmu2k** [comment]
In general its not possible to get a limit above 255, because the limitation of the API the mask of the value has its only a single byte. The 290 fps limit was 255 in value but because the driver had no accurate fps limit in this mode the actual fps was a bit above the value.

You can still use modified CustomSettingNames_en-EN.xml, you just need to place it into the folder. You can also export the embedded version of this file by calling the tool with "-createCSN" parameter.

The exception tells you that you have input an incorrect value, you can still manually input custom values
