### ISSUE TITLE
Not sure if this is the right place? MDPS request

### ISSUE THREAD

**Issue by klepp0906** [Orbmu2k/nvidiaProfileInspector#22]
I know at some point Nvidia Inspector and Nvidia Profile Inspector were forked and im unsure which/by whom was which.  

That being said, theyre both invaluable and ill always have them on hand.

Im currently running an SLI + Surround + accessory display rig and as such one of my gpus runs at >1100mhz and wastes a ton of power/heat.

After tinkering with MDPS ive got it working "almost" ideally.  

I began by using the "by gpu load" option which seemed to be the best fit (and still is).  The caveats I noticed are 1) it causes lag when the game opens before the increase happens (minor and willing to deal with) and 2) if the load drops even for a split second in game, gpu usage will spike causing lag for a second or two.  (much bigger issue)

Now the obvious is to turn down the threshold as far as possible to minimize these instances (which I have done - to 10%)  If i go any lower, mucking around on the desktop can increase the load enough for a short period of time to cause the clock-up.

Even though it was going to be an inconvenience, I decided to bite the bullet and try the "by exe" mode to see if it fared any better.  It did - to an extent.  The usage spike/drop clock spike/drop issue wasnt present.   It also didnt lag on the opening of games as by the time the game loaded full it had already recognized it and clocked up.

Unfortunately I have some fringe cases which make using this mode impossible.  (it was the less ideal maintenence wise anyhow to be fair)  I run steam and I run steam because I have a steam link on several tv's around the house.  Therefore I have steam load at startup on my pc.  Steam doesnt require any gpu, but steam bigpicture mode does.  So when I open big picture mode on a tv, it lags if I dont use "gpu usage" mode because its running at rest-state.  If I add steam.exe to the list, it clocks up at desktop because steam is running in my tray and no way exists that I have found to differentiate steam from steam bigpicture mode.

So, with all that said - What im looking for/hoping can be implemented - is a delay (or a box with a delay setting).  That allows the time under your set Gpu usage before it downclocks.  This way a very short gpu usage drop in game wont cause a clock/frame drop.

Really a means to solve any of the aforementioned would be great but I have no idea what isnt or isnt possible to that end.  Its above my pay-grade =P

Either way, thanks for taking your time to develop this software.  Invaluable to any enthusiast imo.

**Comment by klepp0906** [comment]
Also, the option to save window position incorporated into Nvidia profile inspector would be awesome.  Every time i open it instead of popping up the size and place i last left it (my accessory display) it pops up on my main display(s) in front of whatever im doing.

Minor but nearly everything includes this nowadays. /shrug

**Comment by Orbmu2k** [comment]
wrong place :)

...but you might take a look at this file´: c:\ProgramData\NVIDIA_Inspector\MultiDisplayPowerSaverSettings.xml

  <GpuUsageAttackTimeSec>2</GpuUsageAttackTimeSec>
  <GpuUsageLeaseTimeSec>20</GpuUsageLeaseTimeSec>
  <VpuUsageAttackTimeSec>0</VpuUsageAttackTimeSec>
  <VpuUsageLeaseTimeSec>10</VpuUsageLeaseTimeSec>

**Comment by tomose** [comment]
@Orbmu2k Sorry to post in a closed incident but I didn't want to make a new one that was off topic here.

It seems your email on your website is no longer active "info@orbmu2k.de". May want to check that out. I was going to inquire directly if you had any intention of putting out an updated MDPS with a few changes (namely a way to set a "gpu usage should be < x" type of setting for controlling how low GPU usage in PState0 should be before switching back to Pstate8. So if you have it > 60% trigger Pstate0 and it switches, then you'd be at like 10% in Pstate0 and it'll drop back to Pstate8 since it's lower than the threshold to switch up, but when you're back in Pstate8 it's high usage again and switches, endless loop without a lower threshold to tell it when it's ok to drop back down.

Also, VPU switching has never worked for me, tested with Pascal and Win10. Always blanks out the screen if it activates.
