### ISSUE TITLE
Investigate Website

### ISSUE THREAD

**Issue by JacobWKlein** [Orbmu2k/nvidiaProfileInspector#37]
I've seen this website, and it looks suspicious to me.

Would you consider investigating it, and potentially taking action if it is mischievous (potentially peddling malware) or infringing on copyright?

https://nvidiaprofileinspector.com/

Thanks.

**Comment by Orbmu2k** [comment]
nice find! thank you!

yeah it looks suspicious, but theres nothing i can do about it :(

**Comment by DarkStarSword** [comment]
Looks like it's hosting DeadManWalking's fork - the sha1 of the latest release on that site matches that on his github

**Comment by ValZapod** [comment]
@Orbmu2k @DarkStarSword What is your problem? It is also open source!  https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW

**Comment by JacobWKlein** [comment]
A few problems.

- Open source doesn't mean safe
- Having a secondary source with a differing version number and release structure compared to the original can lead to confusion
- Having a website that doesn't reference the original source at all, and doesn't offer any info about being a fork or having a GitHub repo, is very suspicious to a user who doesn't blindly download.
- Nowhere did they indicate that they are a second source. Only download download download.

Think critically about why this looks suspicious. If you still don't see the problems, then you may be overly trusting in today's digital world.

**Comment by ValZapod** [comment]
@JacobWKlein I download terabytes of software on torrents from rutracker.org. There were never any viruses. They have moderators to check it, you know. I do not have an antivirus and I made a modification in windows policy to turn off windows defender, there were never any problems besides some idiotic adware viruses. Besides that I write viruses, so I can not really use an antivirus.

**Comment by ValZapod** [comment]
https://www.softpedia.com/get/System/System-Info/NVIDIA-Inspector.shtml
Here you are, you should download it here! Really!

**Comment by JacobWKlein** [comment]
I laid out the problems, clearly. They still stand. I rest my case. Good luck.

**Comment by ValZapod** [comment]
@JacobWKlein Okay, maybe you did not understand smth. First, it is MIT license https://github.com/Orbmu2k/nvidiaProfileInspector/blob/master/LICENSE
So you can do ANYTHING with the code. And when I say anything, it also means that you can add a malware inside, register a domain and share a virus as you wish. The author cannot do anything about what domains are registered and nobody should have such access in ideal world because Internet should not be controlled by anybody and domain is your propety! It does look suspicious but if there were viruses then it will not be on first page in Google. It also will be pointed as such in Ublock Origin or Adblock if you use them. You are very naive unfortunately.

**Comment by JacobWKlein** [comment]
I am cautious, informative, and patient.
You are dangerous, illogical, and insulting.

I did my best to serve this community.

Good luck.
