### ISSUE TITLE
Nvidia Frame Rate Limiter Mode missing since when?

### ISSUE THREAD

**Issue by Limeay** [Orbmu2k/nvidiaProfileInspector#97]
When did Nvidia remove this feature from their driver's? I can't find it with Profile Inspector anymore.
I want to retry Delay flip metering or whatever it's called.

**Comment by Hrxn** [comment]
Uh, quite some time, maybe R460 or even a bit earlier...

**Comment by Limeay** [comment]
Oh okay... That's a shame -.-

**Comment by couleurm** [comment]
heard [RTSS ](https://www.guru3d.com/files-details/rtss-rivatuner-statistics-server-download.html) had a good framerate limiter

**Comment by Limeay** [comment]
It's not really about the frame rate limiter i want, i want the mode as it makes panning around with mouse smoother.

**Comment by SixelAlexiS90** [comment]
> It's not really about the frame rate limiter i want, i want the mode as it makes panning around with mouse smoother. Also i have RTSS

can you explain what this "Frame Rate Limiter Mode" did actually if not capping the framerate?

**Comment by Limeay** [comment]
Uhm, before with r460 or earlier the frame rate limiter mode had delay flip by flip metering/other options i can play with. It made panning around in fps games very smooth if you get what that feels like. Unfortunately they no longer have that supported in the drivers and I've already capped my fps in games without the need for Rtss as ingame fps limiters are better supposedly.

**Comment by SixelAlexiS90** [comment]
> Uhm, before with r460 or earlier the frame rate limiter mode had delay flip by flip metering/other options i can play with. It made panning around in fps games very smooth if you get what that feels like. Unfortunately they no longer have that supported in the drivers and I've already capped my fps in games without the need for Rtss as ingame fps limiters are better supposedly.

Yeah, in-game frame limiter are usually much better since they don't try to get a flat line no matter what, which ironically introduce more stuttering.

Could this "flip by flip metering" be something similar to "front edge sync" or "back edge sync" from RTSS?
Take a look and try, I find that in many cases "front edge sync" solve the flat line issues I was talking about, giving the frame time a bit of room to avoid stutters.

You can find the 3 options under "setup" in RTSS, scroll down and on "enable frame limiter" and you will see a top down menu on the right with "async" selected (default cap method of RTSS) and the other two mentioned methods.

If you hover the cursor on the top down menu you will get a more detailed explanation of all three methods, give it a go :)

p.s. the selected method is saved per-profile.
